### ISSUE TITLE
红米K30 Andorid 11 点击按钮没有反应 

### ISSUE THREAD

**Issue by wangjing71** [AnyLifeZLB/CameraXFragment#2]

**Comment by wangjing71** [comment]
2021-07-19 15:12:54.945 10858-11528/com.zenglb.cameraxfragment E/CameraXFragment: Photo capture failed: Failed to write temp file
    androidx.camera.core.ImageCaptureException: Failed to write temp file
        at androidx.camera.core.ImageCapture$2.onError(ImageCapture.java:861)
        at androidx.camera.core.ImageSaver.lambda$postError$2$ImageSaver(ImageSaver.java:319)
        at androidx.camera.core.-$$Lambda$ImageSaver$q5J8WAquxyekKA6et-sNzW3OiJM.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/cameraX/images/CameraX27f77f6e-9e2f-4b78-ae46-3e6cb46127f4.tmp: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at androidx.camera.core.ImageSaver.saveImageToTempFile(ImageSaver.java:118)
        at androidx.camera.core.ImageSaver.run(ImageSaver.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7765)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
        at androidx.camera.core.ImageSaver.saveImageToTempFile(ImageSaver.java:118) 
        at androidx.camera.core.ImageSaver.run(ImageSaver.java:85) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by AnyLifeZLB** [comment]
TargetSDK 改为 30了？
